# syntax=docker/dockerfile:1.7
# 1) Build frontend
FROM node:20-alpine AS fe
WORKDIR /app
COPY ./frontend/package*.json ./frontend/
RUN cd frontend && npm ci
COPY ./frontend ./frontend
RUN cd frontend && npm run build

# 2) Nginx to serve SPA + proxy /api
FROM nginx:alpine
COPY ./api-gateway/nginx.prod.conf /etc/nginx/nginx.conf
COPY --from=fe /app/frontend/dist /usr/share/nginx/html
