services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todo-service:
    build: ./backend/todo-service/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/todo_db?sslmode=disable
      JWT_SECRET: supersecretjwtkey
      PORT: 8080
    expose:
      - "8080"

  api-gateway:
    build: ./backend/api-gateway/
    ports:
      - "8080:80"
    depends_on:
      - todo-service

  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api/v1

volumes:
  postgres_data: