# .air.toml
root = "."
tmp_dir = "tmp"

# 👇 these must be top-level (not under [watcher])
poll = true
poll_interval = 500      # ms
exclude_unchanged = true
follow_symlink = true
delay = "100ms"

[build]
cmd = "go build -o /tmp/app ./main.go"   # or your actual main package path
bin = "/tmp/app"
kill_delay = "200ms"
exclude_regex = ["_test.go"]

# Watch lists stay under top-level keys as well (no [watcher] section)
include_dir = ["."]
exclude_dir = ["vendor", "tmp", ".git"]
include_ext = ["go", "tpl", "tmpl", "html", "env"]

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
app = "white"

[misc]
clean_on_exit = true
