server_name: "messie.arpinfidel.com"
pid_file: /data/homeserver.pid

report_stats: false

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::', '0.0.0.0']
    resources:
      - names: [client, federation]
        compress: false

database:
  name: sqlite3
  args:
    database: /data/homeserver.db

media_store_path: /data/media_store
signing_key_path: "/data/signing.key"

enable_registration: true
registration_shared_secret: "dev_matrix_shared_secret"
enable_registration_without_verification: true

app_service_config_files:
  - /data/appservices/whatsapp-registration.yaml
  - /data/appservices/doublepuppet-registration.yaml

python_paths:
  - /data/custom_modules

modules: []
# modules:
#   - module: block_bot_dms.BlockBotDMs
#     config:
#       bot_mxid: "@whatsappbot:messie.localhost"
#       admins:
#         - "@bridge-admin:messie.localhost"
#       block_dm_invites: true
#       require_prefix_in_dm: false

trusted_key_servers:
  - server_name: "matrix.org"
  
# Silence 'matrix.org' trusted key server warning in dev
suppress_key_server_warning: true
